### PR TITLE
Update value.py

### PR DESCRIPTION
**Pull request by lonelyju**
Added fingerprint of 2020 Subaru Levorg 2.0 VMG

### CODE REVIEW

**Comment by martinl** [comment]
Hi, please also send a route for verification

**Comment by lonelyju** [comment]
Here is a route for your reference:

https://connect.comma.ai/035220d29d178fad/1665703814130/1665709113161

Thanks!

martinl ***@***.***> 於 2022年10月16日 週日 18:38 寫道：

**Comment by lonelyju** [comment]
https://connect.comma.ai/035220d29d178fad/1665963099703/1665970032756
Another route for your reference

Chao-Chin (Kelvin) Chou ***@***.***> 於 2022年10月16日 週日 19:01 寫道：

**Comment by martinl** [comment]
Please open the route in connect, then click More info and copy route name from first line in the menu.
Also make sure you have uploaded all logs and Public access is enabled for the route

**Comment by lonelyju** [comment]
Route name: 035220d29d178fad|2022-10-17--07-31-39--0
Link: https://connect.comma.ai/035220d29d178fad/1665963099703/1665970032756

Route name: 035220d29d178fad|2022-10-14--07-30-14--0
Link: https://connect.comma.ai/035220d29d178fad/1665703814130/1665709113161


martinl ***@***.***> 於 2022年10月17日 週一 21:43 寫道：

**Comment by lonelyju** [comment]
Route name: 035220d29d178fad|2022-10-17--19-15-03--13
Link: https://connect.comma.ai/035220d29d178fad/1666005303772/1666010308805


Chao-Chin (Kelvin) Chou ***@***.***> 於 2022年10月17日 週一 22:49 寫道：

**Comment by martinl** [comment]
Thanks, I checked the route and added the fw values to subaru-community branch

**Comment by lonelyju** [comment]
Great, thanks!

martinl ***@***.***> 於 2022年12月7日 週三 01:16 寫道：

**Pull request closed without merging**
