### PR TITLE
AGNOS 2

### PR DESCRIPTION
**Pull request by ErichMoraga**

### CODE REVIEW

**Comment by AdamSLevy** [comment]
I tested this but I'm getting prompted to update the system on reboot and then "Update failed". I've tried twice and ensured I'm connected to wifi

**Comment by ErichMoraga** [comment]
> I tested this but I'm getting prompted to update the system on reboot and then "Update failed". I've tried twice and ensured I'm connected to wifi

Seems unique to you, so far.  Implemented the change to my old 0.8.7 branch 12 days ago, and works fine.

**Comment by ErichMoraga** [comment]
Does @martinl keep his branches up to date?  If not, I'll just close this commit.  Good luck to the Subie folk out there!

**Comment by ErichMoraga** [comment]
Fork owner seems to be asleep at the wheel.  Closing...

**Comment by martinl** [comment]
Hi

thanks for the PR.
I usually merge from upstream when new openpilot version is released or there is a critical fix to keep things simple

Martin

**Pull request closed without merging**
